services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: olario_api
    ports:
      - "8080:8080"
    environment:
      APP_ENV: ${APP_ENV:-local}
      APP_PORT: ${APP_PORT:-8080}
      DATABASE_URL: ${DATABASE_URL:-}
      REDIS_ADDR: ${REDIS_ADDR:-}
      REDIS_USERNAME: ${REDIS_USERNAME:-}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
      REDIS_DB: ${REDIS_DB:-0}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT:-}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-}
      MINIO_BUCKET: ${MINIO_BUCKET:-}
      MINIO_USE_SSL: ${MINIO_USE_SSL:-false}
      AUTH_ACCESS_TOKEN_SECRET: ${AUTH_ACCESS_TOKEN_SECRET:-}
      AUTH_REFRESH_TOKEN_SECRET: ${AUTH_REFRESH_TOKEN_SECRET:-}
      PROD_SMTP_HOST: ${PROD_SMTP_HOST:-}
      PROD_SMTP_PORT: ${PROD_SMTP_PORT:-587}
      PROD_SMTP_SECURE: ${PROD_SMTP_SECURE:-true}
      PROD_SMTP_USER: ${PROD_SMTP_USER:-}
      PROD_SMTP_PASSWORD: ${PROD_SMTP_PASSWORD:-}
      PROD_SMTP_FROM_ADDRESS: ${PROD_SMTP_FROM_ADDRESS:-}
      SWAGGER_ENABLED: ${SWAGGER_ENABLED:-false}
      SWAGGER_USERNAME: ${SWAGGER_USERNAME:-superadmin}
      SWAGGER_PASSWORD: ${SWAGGER_PASSWORD:-}
